version: '3.7'
services:
    db:
        image: mariadb:latest
        container_name: db
        restart: always
        environment:
            MYSQL_DATABASE: gaon
            MYSQL_USER: root
            MYSQL_PASSWORD: berea6922
            MYSQL_ROOT_PASSWORD: berea6922
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb_data:/var/lib/mysql
    php:
        container_name: php
        build:
            context: ./images/php
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "9000:9000"
        volumes:
            - ./source:/var/www/html:rw
    nginx:
        container_name: nginx
        build:
            context: ./images/nginx
            dockerfile: Dockerfile
        volumes:
            - ./source:/var/www/html:rw
            - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
        depends_on:
            - php
        ports:
            - "80:80"
            - "443:443"
